Removed all hardcoded strings
Gopher-Industries/Guardian pull request #111
Opened 2023-11-18 05:55 UTC by smithhug

All hardcoded strings have been added to strings.xml. Searching the project for hardcoded text will reveal 0 results now. There are no duplicate strings.

2023-11-18 11:05 UTC, el-veee requested changes
Couple minor things, but otherwise looks good

2023-11-18 11:05 UTC, el-veee commented on app/src/main/res/layout/activity_care_plan.xml
> +                android:contentDescription="@string/todo"
I would leave out the TODO ones. Adding appropriate content descriptions to our views will be a separate piece of work, and putting this string here might make android studio think this has a proper content description, when it doesn't

2023-11-18 11:05 UTC, el-veee commented on app/src/main/res/layout/activity_care_plan_summary.xml
> +        xmlns:tools="http://schemas.android.com/tools"
Weird formatting?

2023-11-18 11:05 UTC, el-veee commented on app/src/main/res/layout/activity_caretaker_dashboard.xml
> +                    android:contentDescription="@string/todo"
Same thing about the TODO string

2023-11-19 01:00 UTC, smithhug commented
Removed todo string and replaced referenced with "TODO"

2023-11-19 01:01 UTC, smithhug commented on app/src/main/res/layout/activity_care_plan_summary.xml
> +        xmlns:tools="http://schemas.android.com/tools"
Fixed formatting in recent commit.

2023-11-19 05:11 UTC, el-veee approved these changes

2023-11-20 03:29 UTC, merged