Gp kotlin conversions
Gopher-Industries/Guardian pull request #230
Opened 2024-08-20 06:39 UTC by mirahazall

## Description

Converted the files in gp and nextofkin folders from java to kotlin

### Todos

- [ ] Tested and working locally
- [ ] Code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] Code changes documented
- [ ] Requested review from >= 2 devs on the team (one frontend and one backend recommended)

### How to test

[Add detailed steps to test the changes that have been made]

### Screenshots and/or Gifs

[Insert screenshots and/or gifs showing the graphic representation of the change]

### Associated MS Planner Tasks

- [Task Title](http://ms_planner_task_link.com)
- [Task Title](http://ms_planner_task_link.com)

### Known Issues

[Describe any known issue with this change]

2024-08-21 13:41 UTC, AsherAli22 approved these changes

2024-08-21 13:42 UTC, AsherAli22 commented
Good Work @mirahazall

2024-08-22 00:20 UTC, Onwa1kenobi reviewed
Very good work @mirahazall. Just need to actually fill out the PR template when creating a PR.

2024-08-22 00:20 UTC, Onwa1kenobi commented on app/build.gradle
You have performed some version bumps here. Can you also mention this in the PR description?

2024-08-22 00:22 UTC, Onwa1kenobi requested changes
The Git workflow build failed due to some code violations flagged by our spotless lint. Run './gradlew :app:spotlessApply' to fix these violations, and then commit and push again.

2024-08-22 00:39 UTC, mirahazall commented on app/build.gradle
Hi, I will mention the version modifications. I ran the ./gradlew :app:spotlessApply command and got an error that says there is a mismatch between the Java version our Gradle build is configured to use and the Java version required by some of the dependencies, like google-services and the Android Gradle Plugin. These dependencies expect Java 11, but our project is set up for Java 8. I'm not sure how to fix this incompatibility issue. In our build.gradle file, Java version is specified as 17. I'm not sure why spotless thinks we are using Java 8

2024-08-22 03:05 UTC, Onwa1kenobi commented on app/build.gradle
That is weird. I will take a look.

2024-08-22 03:33 UTC, Onwa1kenobi commented on app/build.gradle
Looks good now.

2024-08-22 03:33 UTC, Onwa1kenobi approved these changes

2024-08-28 22:38 UTC, merged